### ISSUE TITLE
Test note

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/correspondence_tool_public#61]

**Comment by aliuk2012** [comment]
cool note

**Comment by aliuk2012** [comment]
![screen shot 2016-09-21 at 14 34 59](https://cloud.githubusercontent.com/assets/3441519/18712979/a4b1c9ce-8008-11e6-80e1-ce8c6cef9e82.png)
I like how it shows where it is in the project and which project it relates too.....

BTW you can setup multiple project boards on github

**Comment by misaka** [comment]
Related to #60
